/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToolsPanels;

import Shapes.Filler;
import Shapes.Picker;
import Shapes.Rectangle;
import Shapes.Shapes;
import WhateverPaint.MainWindow;
import java.util.ArrayList;
import java.util.Stack;

/**
 *
 * @author Gehad
 */
public class EditBox extends javax.swing.JPanel {
   private Stack <Shapes> redoo;
    private Shapes temp1;
    private Shapes temp2;
    private int flag1=0;
    private int flag2=0;
    private ArrayList<Shapes> prevShapes2 = new ArrayList();
    private Canvas cc;
    public EditBox() {
        initComponents();
       
        this.redoo = new Stack();
        redo.setEnabled(false);
        undo.setEnabled(false);
    }
    public void setCanvas(Canvas c)
    {
        cc=c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fill = new javax.swing.JButton();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        picker = new javax.swing.JButton();

        setBackground(new java.awt.Color(40, 40, 40));
        setMaximumSize(new java.awt.Dimension(135, 80));

        fill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/fill-color.png"))); // NOI18N
        fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillActionPerformed(evt);
            }
        });

        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit-undo.png"))); // NOI18N
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });

        redo.setBackground(new java.awt.Color(83, 83, 83));
        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit-redo.png"))); // NOI18N
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });

        picker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/color-picker.png"))); // NOI18N
        picker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(fill, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redo)
                    .addComponent(fill)
                    .addComponent(picker)
                    .addComponent(undo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillActionPerformed
Canvas.setShape(new Filler());
        MainWindow.old=fill;      
    }//GEN-LAST:event_fillActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
     if (!Canvas.getPrevShapes().isEmpty()){
          undo.setEnabled(true);
          flag1++;
          prevShapes2 = Canvas.getPrevShapes();
          temp1 = prevShapes2.get(prevShapes2.size()-1);
          redoo.push(temp1);
          prevShapes2.remove(prevShapes2.size()-1);
          
          Canvas.setPrevShapes(prevShapes2);
          cc.repaint();
          redo.setEnabled(true);
          
      } if (prevShapes2.size()==0) 
        {undo.setEnabled(false);
        } 
    }//GEN-LAST:event_undoActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        temp2 = redoo.pop();
        prevShapes2.add(temp2);
        undo.setEnabled(true);
        Canvas.setPrevShapes(prevShapes2);
        flag2++;
        cc.repaint();
        System.out.println(prevShapes2.size());
        if (flag1==flag2){
            redo.setEnabled(false);
        }
    }//GEN-LAST:event_redoActionPerformed

    private void pickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickerActionPerformed
       Canvas.setShape(new Picker());
        MainWindow.old=picker; 
    }//GEN-LAST:event_pickerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fill;
    private javax.swing.JButton picker;
    public static javax.swing.JButton redo;
    public static javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}
